### ISSUE TITLE
Huge issue

### ISSUE THREAD

**Issue by SuckAtCP** [cprime0916/std-wame#3]
Documentation where

**Comment by cprime0916** [comment]
This project is temporarily disabled, should you have any enquiries, please contact cprime.

**Comment by SuckAtCP** [comment]
cprime : 🤓

**Comment by cprime0916** [comment]
🤓

**Comment by SuckAtCP** [comment]
literally you -> 🤓 🤓 🤓

**Comment by cprime0916** [comment]
Ok
